
base_model:
  model_name: "swin_tiny_patch4_window7_224"  
  image_size: [224, 224]
  num_classes: 4
  learning_rate: 0.001
  weight_decay: 0.001
  freeze_base: true

training:
  epochs: 1
  batch_size: 32
  val_split: 0.2 
  learning_rate: 0.001
  weight_decay: 0.005
  optimizer: "adamw"
  scheduler: "cosine"   # options: step, cosine, none
  step_size: 7          # only used if scheduler=step
  gamma: 0.1            # only used if scheduler=step

evaluation:
  batch_size: 16


